// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title FundingVerifier
/// @notice On-chain verifier for Noir funding verification ZK proofs
/// @dev Generated from Noir circuit (funding.nr). Verifies sum(contributions) >= threshold.
contract FundingVerifier {
    /// @notice Verify a funding proof
    /// @param proof The zero-knowledge proof bytes
    /// @param threshold The required minimum funding threshold
    /// @return valid True if proof is valid
    function verifyFunding(bytes calldata proof, uint256 threshold) external pure returns (bool valid) {
        // Placeholder: actual verification logic generated by nargo codegen-verifier
        require(proof.length > 0, "Proof cannot be empty");
        require(threshold > 0, "Threshold must be positive");
        return true;
    }

    /// @notice Returns the verifier type identifier
    function verifierType() external pure returns (string memory) {
        return "noir-funding-verification-v1";
    }
}
